import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { API_ROUTES, BROWSER_ROUTES, SERVER_ONLY_ROUTES } from "@/lib/api/routes";
import { proxyTarget } from "@/lib/api/backend-proxy";

/** Holds the frontend's idea of the API against the API's own route table.
 *
 * backend-routes.json is generated by backend/scripts/export_routes.py from the
 * live OpenAPI document, and backend/tests/test_route_manifest.py fails when it
 * is stale. So a path renamed in FastAPI, a method changed, or a query parameter
 * that moved into the body breaks here — at `npm test` — instead of at runtime.
 */

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const manifest = JSON.parse(readFileSync(resolve(ROOT, "lib/api/backend-routes.json"), "utf8")) as {
  routes: Array<{ method: string; path: string; query: string[]; required_query: string[] }>;
};

const find = (path: string, method: string) =>
  manifest.routes.find((route) => route.path === path && route.method === method);

describe("frontend route registry vs FastAPI", () => {
  it("has a manifest that looks like the real API", () => {
    expect(manifest.routes.length).toBeGreaterThan(15);
    expect(find("/", "GET")).toBeDefined();
  });

  it.each(API_ROUTES.map((route) => [`${route.method} ${route.path}`, route] as const))(
    "%s exists in FastAPI",
    (_label, route) => {
      const backend = find(route.path, route.method);
      expect(backend, `${route.method} ${route.path} is not a route this backend serves`).toBeDefined();
    },
  );

  it.each(
    API_ROUTES.filter((route) => route.query?.length).map((route) => [`${route.method} ${route.path}`, route] as const),
  )("%s sends only query parameters FastAPI declares", (_label, route) => {
    const backend = find(route.path, route.method)!;
    const unknown = route.query!.filter((name) => !backend.query.includes(name));
    expect(unknown, `not accepted by the backend: ${unknown.join(", ")}`).toEqual([]);
  });

  it("sends every query parameter the backend requires", () => {
    for (const route of API_ROUTES) {
      const backend = find(route.path, route.method)!;
      const missing = backend.required_query.filter((name) => !(route.query ?? []).includes(name));
      expect(missing, `${route.method} ${route.path} must send: ${missing.join(", ")}`).toEqual([]);
    }
  });

  it("declares no route twice", () => {
    const keys = API_ROUTES.map((route) => `${route.method} ${route.path}`);
    expect(new Set(keys).size).toBe(keys.length);
  });
});

describe("proxy allowlist is derived, not hand-written", () => {
  it("forwards every browser route", () => {
    for (const route of API_ROUTES.filter((entry) => entry.surface === "browser")) {
      const segments = route.path.replace(/^\//, "").split("/");
      expect(proxyTarget("http://api", segments, route.method, "")).toBe(`http://api${route.path}`);
    }
  });

  it("refuses every server-only route on both methods", () => {
    for (const route of SERVER_ONLY_ROUTES) {
      const segments = route.path.replace(/^\//, "").split("/");
      expect(proxyTarget("http://api", segments, "GET", "")).toBeNull();
      expect(proxyTarget("http://api", segments, "POST", "")).toBeNull();
    }
  });

  it("refuses every route the app does not call at all", () => {
    const declared = new Set(API_ROUTES.map((route) => route.path));
    const untouched = manifest.routes.filter((route) => !declared.has(route.path));
    expect(untouched.length).toBeGreaterThan(5); // /train, /boreholes, /priors, …
    for (const route of untouched) {
      const segments = route.path.replace(/^\//, "").split("/");
      expect(proxyTarget("http://api", segments, route.method, "")).toBeNull();
    }
  });

  it("keeps the browser set to the two routes the Explorer needs", () => {
    expect(Object.keys(BROWSER_ROUTES).sort()).toEqual(["predict/point", "prospectivity/heatmap"]);
  });
});
