"""The route manifest the frontend is checked against must match this app.

frontend/lib/api/backend-routes.json is generated by scripts/export_routes.py
and consumed by the frontend's route-registry test, which is how a renamed path
or a query parameter that moved into the body stops being a runtime 404 and
becomes a failing test. That only works while the file is current, so this test
regenerates it in memory and refuses a stale one.

Fix a failure by running:  python scripts/export_routes.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.export_routes import MANIFEST_PATH, manifest  # noqa: E402


@pytest.fixture(scope="module")
def generated() -> dict:
    return manifest()


@pytest.fixture(scope="module")
def checked_in() -> dict:
    if not MANIFEST_PATH.exists():
        pytest.fail(f"{MANIFEST_PATH} is missing — run python scripts/export_routes.py")
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def test_the_manifest_is_not_stale(generated: dict, checked_in: dict) -> None:
    current = {(row["method"], row["path"]) for row in generated["routes"]}
    recorded = {(row["method"], row["path"]) for row in checked_in["routes"]}
    added = sorted(current - recorded)
    removed = sorted(recorded - current)
    assert not added and not removed, (
        f"frontend/lib/api/backend-routes.json is stale — added {added}, removed {removed}. "
        "Run: python scripts/export_routes.py"
    )


def test_query_parameters_are_recorded_accurately(generated: dict, checked_in: dict) -> None:
    current = {(row["method"], row["path"]): row for row in generated["routes"]}
    for row in checked_in["routes"]:
        live = current[(row["method"], row["path"])]
        assert row["query"] == live["query"], f"{row['method']} {row['path']} query parameters changed"
        assert row["required_query"] == live["required_query"], (
            f"{row['method']} {row['path']} required query parameters changed"
        )


def test_the_manifest_covers_the_routes_the_frontend_depends_on(checked_in: dict) -> None:
    """A short, explicit floor. If one of these disappears, the frontend has a
    dead page, and the failure should name the route rather than a count."""
    recorded = {(row["method"], row["path"]) for row in checked_in["routes"]}
    for expected in [
        ("GET", "/"),
        ("GET", "/dashboard/summary"),
        ("GET", "/forecast"),
        ("GET", "/production/history"),
        ("GET", "/shortfall/risk"),
        ("GET", "/recommendations"),
        ("GET", "/prospectivity/heatmap"),
        ("POST", "/predict/point"),
    ]:
        assert expected in recorded, f"{expected[0]} {expected[1]} is no longer served"


def test_export_check_mode_agrees(capsys: pytest.CaptureFixture[str]) -> None:
    """The same staleness check the developer runs by hand."""
    from scripts.export_routes import main

    assert main(["--check"]) == 0
