/** Every backend route this app calls, declared once.
 *
 * Two things kept drifting apart and nothing caught either of them:
 *
 *   1. What the frontend requests vs. what FastAPI serves. A renamed path or a
 *      query parameter that became a body field still compiles and still passes
 *      the unit suite; it fails as a 404 in front of whoever is watching.
 *   2. What the browser requests vs. what `/api/backend` forwards. The proxy
 *      allowlist is deliberately narrow, so a loader that moves from a Server
 *      Component into a client component would start being refused by this
 *      app's own proxy.
 *
 * This table is the one place both are stated, and two tests turn it into
 * evidence rather than a claim:
 *
 *   tests/unit/route-registry.test.ts  — every entry exists in FastAPI with this
 *     method and these query parameters (backend-routes.json, regenerated by
 *     backend/scripts/export_routes.py and enforced by a backend test).
 *   tests/unit/browser-surface.test.ts — walks the import graph from every
 *     "use client" file and asserts the set of routes reachable in a browser is
 *     exactly the set marked `surface: "browser"` here.
 *
 * `surface` is the security boundary. `/api/backend` is this app's only
 * unauthenticated door to an expensive API, so it forwards the browser set and
 * nothing else. Widening it to routes the browser never calls would add reachable
 * surface and buy nothing — see docs/api-surface.md.
 */

export type RouteSurface = "browser" | "server";

export interface RouteSpec {
  /** The FastAPI path, exactly as the app declares it (`{}` for parameters). */
  readonly path: string;
  readonly method: "GET" | "POST";
  /** `browser` = reachable from a client component, so it must be proxied.
   *  `server` = only ever called from a Server Component or route handler. */
  readonly surface: RouteSurface;
  /** Query parameters this app sends. Checked against FastAPI's own list. */
  readonly query?: readonly string[];
  /** Where the request is issued, and why it sits on this surface. */
  readonly calledBy: string;
}

export const API_ROUTES: readonly RouteSpec[] = [
  {
    path: "/prospectivity/heatmap",
    method: "GET",
    surface: "browser",
    query: ["min_lon", "min_lat", "max_lon", "max_lat", "grid_size", "mask"],
    calledBy: "lib/api/heatmap.ts via hooks/use-prospectivity-surface.ts — the Explorer refetches on every mask change",
  },
  {
    path: "/predict/point",
    method: "POST",
    surface: "browser",
    // `mask` is a QUERY parameter; PredictPointIn carries only lat/lon, so a
    // mask placed in the body is dropped and "none" silently applied.
    query: ["mask"],
    calledBy: "lib/api/predictions.ts via hooks/use-prediction.ts — scores the selected site",
  },
  {
    path: "/dashboard/summary",
    method: "GET",
    surface: "server",
    calledBy: "lib/api/dashboard.ts via lib/api/load.ts — awaited in app/(workspace)/operations/page.tsx",
  },
  {
    path: "/forecast",
    method: "GET",
    surface: "server",
    query: ["horizon"],
    calledBy: "lib/api/forecast.ts via lib/api/load.ts — operations and production pages",
  },
  {
    path: "/production/history",
    method: "GET",
    surface: "server",
    query: ["start", "end"],
    calledBy: "lib/api/forecast.ts via lib/api/load.ts — the chart series and the last observed month",
  },
  {
    path: "/shortfall/risk",
    method: "GET",
    surface: "server",
    calledBy: "lib/api/shortfall.ts via lib/api/load.ts — allowed to fail independently of the forecast",
  },
  {
    path: "/recommendations",
    method: "GET",
    surface: "server",
    query: ["mine_name", "limit"],
    calledBy: "lib/api/recommendations.ts via lib/api/load.ts — the review register",
  },
  {
    path: "/recommendations/scenario/{month}",
    method: "GET",
    surface: "server",
    query: ["mine_name", "limit"],
    // Exported for the historical-replay demo; no page calls it today. Declared
    // so it is still checked against FastAPI rather than rotting unnoticed.
    calledBy: "lib/api/recommendations.ts (fetchScenarioRecommendations) — exported, no current caller",
  },
] as const;

/** The routes the browser may reach, as `path without leading slash -> method`.
 *
 * Parameterised paths cannot be matched by the proxy's exact lookup, so a
 * browser route carrying `{}` is a build-time error here rather than a 404 that
 * only appears when someone clicks the feature.
 */
export const BROWSER_ROUTES: Readonly<Record<string, "GET" | "POST">> = Object.freeze(
  Object.fromEntries(
    API_ROUTES.filter((route) => route.surface === "browser").map((route) => {
      if (route.path.includes("{")) {
        throw new Error(
          `Browser route ${route.path} has a path parameter, which the proxy cannot match. ` +
            `Give it an exact path or move it to the server surface.`,
        );
      }
      return [route.path.replace(/^\//, ""), route.method];
    }),
  ),
);

/** Routes deliberately NOT reachable from the browser, for the proxy tests and
 * the documentation to assert against. */
export const SERVER_ONLY_ROUTES: readonly RouteSpec[] = API_ROUTES.filter(
  (route) => route.surface === "server",
);
